services:
  db:
    image: postgres:15-alpine
    container_name: polyclinic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Agl_159_zvM
      POSTGRES_DB: polyclinic_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polyclinic_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:  .
    container_name: polyclinic
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/polyclinic_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Agl_159_zvM
    volumes:
      - ./app-logs:/app/logs
volumes:
  postgres_data: