spring:
  datasource:
    url: jdbc:postgresql://db:5432/polyclinic_db
    username: postgres
    password: Agl_159_zvM
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true