spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/polyclinic_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true